# Generated by Django 3.0 on 2020-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sub_name', models.CharField(max_length=300)),
                ('descraption', models.TextField()),
                ('price', models.FloatField()),
                ('descount_price', models.FloatField()),
            ],
        ),
    ]
