# Generated by Django 3.0 on 2020-04-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20200406_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='user',
        ),
        migrations.AddField(
            model_name='refund',
            name='email',
            field=models.EmailField(default='admin@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
