# Generated by Django 3.0 on 2020-04-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200407_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adresse',
            name='adresse_type',
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
