# Generated by Django 3.0 on 2020-04-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_auto_20200407_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresse',
            name='adresse_type',
            field=models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Shipping', to='products.Adresse'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
