# Generated by Django 3.0 on 2020-04-07 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_auto_20200407_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='defualt',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
